#!/bin/sh

# Set CHARLCD_PATH to where Adafruit_CharLCD is locate on your system
CHARLCD_PATH=/home/pi/python/Adafruit-Raspberry-Pi-Python-Code/Adafruit_CharLCD/

export PYTHONPATH=$PATH:${CHARLCD_PATH}
python display-hashtag.py $@
